name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4.1"
      - run: opam install -y --deps-only --with-test .
      - run: opam exec -- dune build @all
      - run: opam exec -- dune test
